Javascript: Project Todo
emmanuelkamala/todos pull request #1
Opened 2020-06-10 08:32 UTC by emmanuelkamala

In this project:

A user can add a todo and inside can create a list of todos related to a todo.

- A user can edit a todo list
- A user can create a due date
- A user can set a priority of a todo
- A user can delete a todo

2020-06-10 19:55 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED 

Hi @emmanuelkamala good job working on this, everything works fine :+1:  but there is just one thing left, Github actions is not set for this project so there is no check for errors,  please look into setting Github actions, do this and request for another review :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask:

2020-06-10 20:02 UTC, emmanuelkamala commented
[@Oghenebrume50 ](https://github.com/Oghenebrume50) What do you mean by GitHub actions?, I have not seen that requirement from the project description.

2020-06-10 22:01 UTC, shloch commented
I see that it's not yet emphasised on the requirements 
Read about it here --> [https://microverse.zendesk.com/hc/en-us/articles/360049654493](https://microverse.zendesk.com/hc/en-us/articles/360049654493) 

(just for the knowledge)

2020-06-10 22:12 UTC, shloch requested changes
## Hello @emmanuelkamala , 
Thanks for including Stickler.....am sorry, i really want to give a thumbs up, but i get a console error...... delete all your cache at your level and test project again,

Anyways i hope i am not alone..........This is what i get after trying several times
Please kindly debug it

![Screen Shot 2020-06-10 at 11 16 24 PM](https://user-images.githubusercontent.com/40712459/84324052-dc105980-ab6f-11ea-82dd-794b40fcee38.png)

2020-07-26 22:54 UTC, emmanuelkamala commented
Hi, 
I have corrected the error that was causing the app to not create projects. Now it is working fine.

2020-07-27 06:14 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED

Hi @emmanuelkamala  awesome effort getting everything to work at this level, :clap:  I think you have done really well, there is just one thing left to do :slightly_smiling_face: 

The todo should be editable ![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/ui_requirement.png) I currently see an edit icon but the implementation has not be made yet it still toggles :slightly_smiling_face: 

Please look into that and rrequest for another review :+1: 

PS: About the Github action that was my error, I felt it has been made mandatory already, so sorry :pray:  :slightly_smiling_face: 


**RAPHAEL NORIODE** :mask:  stay_safe

2020-07-27 22:22 UTC, emmanuelkamala commented
I have corrected the 'Edit' Functionality in the app that was not working correctly.

2020-07-28 07:55 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED

Hi @emmanuelkamala awesome work this looks good to me, but please fix the failing linter check, it is very important. 

Please make changes and request for another review :+1:  

**RAPHAEL NORIODE** :mask: stay_safe

2020-07-28 08:41 UTC, emmanuelkamala commented
These ESLinting errors are not making sense to me, no matter what I try to correct what they say, it's not working and some of them are meaningless, like they say, 'import' keyword is a reserved keyword, or I should not use 'let' or 'const'. I have tried to configure a parser that converts it to the old ES5 syntax and makes it read like ES6 but, it still is not working. I have tried googling the solution but can't seem to find one that is working. Please help if you can understand what it means and how to correct it.

2020-07-28 08:52 UTC, emmanuelkamala commented
All the errors that the ESLint is projecting, don't make sense totally. It says, I should have space between my if and the brackets, while none of my code is not spaced between the brackets, also it says, IIFE should have parenthesis, while all my IIFEs have that, it says, I should not use var, while I have not used var in any of my code. What should I correct then? and what is the point of this ESLint if itself is not making any sense?

2020-07-28 08:55 UTC, emmanuelkamala commented
It's like ESLint is just wasting time trying to correct stuff that are just correct from the start.

2020-07-28 15:43 UTC, fatymahmed requested changes
## Hi @emmanuelkamala,

**Please fix the linter errors as mentioned, otherwise, the project cannot be approved**
I'll reach out to you on slack so we can fix linter errors

## Status: Changes Required ♻️

2020-07-29 13:53 UTC, shshamim63 requested changes
## :recycle: Required Changes :recycle: 
___
Hi @emmanuelkamala :wave: 
Your project is complete based on the functionality :clap: . But based on the linter configuration, you can not change the configuration of it. If you think that any rules are necessary to include please create an issue in this [link](https://github.com/microverseinc/linters-config/tree/master/javascript). Please remove the changes you have added on the config file and resolve the errors. After that send the final code review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-07-29 13:53 UTC, shshamim63 commented on .eslintrc.json
> +      "webpack-config.js"
Please do not make any changes to the config files. 
![image](https://user-images.githubusercontent.com/38625956/88806827-be0bc080-d1d2-11ea-8f3f-ebd20c333e1b.png)
For resolving them please read the error messages carefully the solution is also in there.

2020-08-24 22:07 UTC, emmanuelkamala commented
I accidentally submitted a milestone that was one finished, as I had so many milestones to submit for completion, and I ended up submitting this one which was not done yet.

2020-08-25 07:23 UTC, Oghenebrume50 approved these changes
### APPROVED

Hi @emmanuelkamala you have done really well with this, kudos for making changes for every review done on this project, this looks good to me now, please merge and move on

**This is approved**

**RAPHAEL NORIODE** :mask: STAY_SAFE

2020-08-25 07:30 UTC, emmanuelkamala commented
@Oghenebrume50, @shloch, @fatymahmed, @shshamim63 Thank you all.

2020-08-25 07:31 UTC, merged